#!/bin/bash

sudo yabai --load-sa

# Enable tiling
yabai -m config layout stack
#yabai -m config --space 5 layout stack

# Exceptions - app
yabai -m rule --add app="^System Preferences$" manage=off layer=above
yabai -m rule --add app="^Finder$" manage=off layer=above
yabai -m rule --add app="^Karabiner-Elements$" manage=off layer=above
yabai -m rule --add app="^Karabiner-EventViewer$" manage=off layer=above
yabai -m rule --add app="^System Information$" manage=off layer=above
yabai -m rule --add app="^Disk Utility$" manage=off layer=above
yabai -m rule --add app="^Spotify$" manage=off layer=above
yabai -m rule --add app="^The Unarchiver$" manage=off layer=above
yabai -m rule --add app="^zoom.us$" manage=off layer=above
yabai -m rule --add app="^Alfred$" manage=off layer=above
yabai -m rule --add app="^Terminal$" manage=off layer=above 
yabai -m rule --add app="^WireGuard$" manage=off layer=above 

yabai -m rule --add app="^Discord$" space=^5
yabai -m rule --add app="^WhatsApp$" space=^5


# Exceptions - title
yabai -m rule --add title="^Welcome to PyCharm$" manage=off layer=above
yabai -m rule --add title="[pP]references" manage=off layer=above
yabai -m rule --add title="[lL]ibrary" manage=off layer=above
yabai -m rule --add title="[iI]nstall" manage=off layer=above
yabai -m rule --add title="[uU]pdate" manage=off layer=above

yabai -m rule --add app="iTerm2" title="Launcher" manage=off layer=above grid=5:5:1:1:3:3 border=off sticky=on
yabai -m rule --add app="Microsoft Teams" title="" manage=off layer=above


# Focus and mouse
yabai -m config focus_follows_mouse autoraise

# Padding for bar
yabai -m config top_padding 34

# Border
yabai -m config window_border on
yabai -m config window_border_width 6
yabai -m config active_window_border_color 0xFFa6da95
yabai -m config normal_window_border_color 0x00ffffff
yabai -m config insert_feedback_color 0xFF8aadf4

# When window closed, make sure something is focused (if possible)
yabai -m signal --add event=window_destroyed action=~/CustomScripts/focus.sh
